# -*- coding: utf-8 -*-
"""CUSTOMER_SHOPPING_BEHAVIOUR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kR5rPPzpAjBU8EE5HznUOiIJF0_2NmB
"""

import pandas as pd

df = pd.read_csv('/content/customer_shopping_behavior.csv')

df.head()

df.info()

df.describe(include='all')

df.isnull().sum()

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

df.columns

df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

df.columns

# create a new column age_group

labels = ['young_age','adult','middle_ages','senior']
df['age_group'] = pd.qcut(df['age'],q = 4,labels= labels)

df.columns

df[['age','age_group']].head(100)

df.frequency_of_purchases.unique()

# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Annually' : 365,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Monthly' : 30,
    'Every 3 Months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

#comapring two column values for removing unwanted columns

(df['discount_applied']==df['promo_code_used']).all()

# Dropping promo code used column

df = df.drop('promo_code_used',axis = 1)

df.columns

df.head(10)

df = df.drop('frequency_of_purchases',axis = 1)

df.head(10)