select * from CUSTOMER_SHOPPING_BEHAVIOUR;

-- Total revenue generated by male vs female customers
select gender, sum(purchase_amount) as Revenue
from CUSTOMER_SHOPPING_BEHAVIOUR
group by gender;

-- customers used discount but still spent more than average purchase amount

select customer_id,purchase_amount
from CUSTOMER_SHOPPING_BEHAVIOUR
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from CUSTOMER_SHOPPING_BEHAVIOUR);

-- Top 10 products with highest average rating

select top 10 item_purchased,ROUND(avg(review_rating),2) as Average_Rating
from CUSTOMER_SHOPPING_BEHAVIOUR
group by item_purchased
order by avg(review_rating) desc;

-- compare average purchase amounts between standard and express shipping

select shipping_type,ROUND(avg(purchase_amount),2)
from CUSTOMER_SHOPPING_BEHAVIOUR
where shipping_type in ('Standard','Express')
group by Shipping_type;

-- Do subscribed customers spend more ? compare average spend and total revenue between subscribed and non-subscribed customers

select subscription_status,COUNT(customer_id) as Total_Customers,ROUND(avg(purchase_amount),2) as Average_spend,sum(purchase_amount) as Total_Revenue
from CUSTOMER_SHOPPING_BEHAVIOUR
group by subscription_status
order by Average_spend,Total_Revenue desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?

select Top 5 item_purchased,COUNT(item_purchased) as No_of_Purchases
from CUSTOMER_SHOPPING_BEHAVIOUR
where discount_applied = 'Yes'
group by item_purchased
order by No_of_Purchases desc ;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

With Customer_Type as (
select customer_id,previous_purchases,
CASE 
	 WHEN previous_purchases <=5 Then 'New'
	 WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
	 WHEN previous_purchases > 20 THEN 'Loyal Based'
	 End as Customer_Segment
from CUSTOMER_SHOPPING_BEHAVIOUR)
select Customer_segment, count(*) as Number_of_Customers
from Customer_Type
group by Customer_Segment;

-- What are the top 3 most purchased products within each category?

with item_counts as(
 select category, item_purchased, count(customer_id) as total_order,
 ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from CUSTOMER_SHOPPING_BEHAVIOUR
Group by category,item_purchased
)
select item_rank,category,item_purchased,total_order
from item_counts
where item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as Repeat_Buyers
from CUSTOMER_SHOPPING_BEHAVIOUR
WHERE previous_purchases > 5
group by subscription_status;

--  What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount) as Revenue_Contribution
from CUSTOMER_SHOPPING_BEHAVIOUR
group by age_group
order by Revenue_Contribution desc;

